### ISSUE TITLE
Compile error CustomDialog

### ISSUE THREAD

**Issue by DarthSidius** [oleg-shilo/wixsharp#511]
https://github.com/oleg-shilo/wixsharp/blob/67c57624b5bc3db389f35ee6dd540da33070409d/Source/Templates/ProjectTemplates/WixSharp%20Managed%20Setup%20-%20Custom%20Dialog/CustomDialog.cs#L20

**error CS1929: 'ISession "does not contain a definition for "GetEmbeddedBitmap", and the most appropriate overloaded extension method "Extensions.GetEmbeddedBitmap (Session, string)" requires the presence of a" Session "type**

Line 20 must be: `banner.Image = MsiRuntime.MsiSession.GetResourceBitmap("WixUI_Bmp_Banner");`

**Comment by oleg-shilo** [comment]
Thank you.
Fixed. Will be available in the next release

**Comment by keshavkaul** [comment]
Hi @oleg-shilo 
This isssue is still present when adding a Wixsharp UI Dialog Item

**Comment by oleg-shilo** [comment]
You are right.
The very reported issue of ProjectTemplate is fixed but the ItemTemplate is also affected.

Dione. Fixed in v1.7.2 of the VS project template extension: https://marketplace.visualstudio.com/items?itemName=OlegShilo.WixSharpProjectTemplates

**Comment by keshavkaul** [comment]
@oleg-shilo Thanks for the prompt reply and fix.
I want to thank you for creating this life saver of a project for people that are more comfortable working with c# than custom xml language. Cheers!

**Comment by oleg-shilo** [comment]
Thank you @keshavkaul, And thank you for your support.

I do know very well the developer frustration when using something as barely manageable as raw WiX when you need to create something as simple as a distribution of a few files.

I also know the manager frustration when ensuring ensure that the team has a developer with special exotic skills only because we need to deploy the product. Even though this skill is not reusable for any other domain.

And this is the reason why I created WixSharp and still maintain and evolve it. Even though, and this is quite ironic, the last time I authored msi was about 7 years ago. :) 

I just don't want my fellow developers to struggle so I keep pushing.
